### ISSUE TITLE
Install failure

### ISSUE THREAD

**Issue by DieSteinhose** [PedalPi/Physical#8]
Hello, when I try to install this error message comes

`pi@raspberrypi:~ $ sudo pip install PedalPi-Raspberry-Physical
Collecting PedalPi-Raspberry-Physical
  Using cached https://files.pythonhosted.org/packages/a7/5f/ccd5a42d279d5e617da8c4af611ee133f99f68a4c8e910ab508805a60656/PedalPi-Raspberry-Physical-0.2.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-1eaI6d/PedalPi-Raspberry-Physical/setup.py", line 30, in <module>
        long_description=readme(),
      File "/tmp/pip-build-1eaI6d/PedalPi-Raspberry-Physical/setup.py", line 22, in readme
        with open(path.join(here, 'README.rst'), encoding='UTF-8') as f:
    TypeError: 'encoding' is an invalid keyword argument for this function

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-1eaI6d/PedalPi-Raspberry-Physical/`

**Comment by SrMouraSilva** [comment]
Hello @Logimann,  probably the `sudo pip` corresponds to the python 2 pip.
Please, try only `pip install PedalPi-Raspberry-Physical` without `sudo`.

Also, you can use `pip3` instead `pip`

**Comment by DieSteinhose** [comment]
Thanks, it works with pip3.
